services:
  - type: web
    name: monSiteWeb
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn monSiteWeb.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
