services:
  - type: web
    name: monSiteWeb
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn monSiteWeb.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: monSiteWeb-db
          property: connectionString
